### ISSUE TITLE
CBMAAObjects:ObjectID

### ISSUE THREAD

**Issue by steads** [american-art/cbm#7]
ObjectID: This is a temporary system identifier used to tie records together between files and as such there is no need to map it.

**Comment by ghost** [comment]
Wouldn't ObjectID be the way to tie each of the CSVs representing each section of our database together? For example, Artist doesn't appear in Objects because Artists are Constituents, so ObjectID is included in Constituents in order to identify that Painting X applies with Artist Y. If this is irrelevant to the mapping my apologies.

**Comment by caknoblock** [comment]
Yes, we definitely need to keep the ObjectID in the dataset.  Stephen just means that we don’t need to put it into the RDF.  However, it will have to go into the RDF since that is the way Karma links the data across sources.

**Comment by ghost** [comment]
Oh ok, Good to know, thanks for clarifying. My apologies I'm a rookie at this.

**Comment by steads** [comment]
In 3M rather than Karma there is no need to keep such temporary Foreign Keys in the published LOD as internal temporary IDs are not really of any interest for integration. However whatever you need for your tool of choice.

**Comment by steads** [comment]
Why not use ObjectNumber? This has the advantage that it is a real identifier that is in use in the real world (i.e. beyond the confines of the IT system)
