### ISSUE TITLE
Creation Date Display

### ISSUE THREAD

**Issue by ghost** [american-art/cbm#75]
http://browse.americanartcollaborative.org/object/cbm/20112.html

This record is illustrative of how dates are displayed on the Browse app demo.

1904-01-01 to 1904-12-31

In our database the creation dates on the actual Date Tables for BeginDate and EndDate for this Object are

1904 and 1904.

Personally, I think displaying dates in a default Y/M/D format for Objects which don't have that information entered (which for sure is 99% of our objects and a decent chunk of most other institutions) seems odd.

John Peto's Self Portrait with Rack Picture was painted in 1904, but we don't know when in that year he painted it or for how long. I understand in the actual dataset needing to keep dates to a consistent format, but on the Browse app especially this seems odd as it is outside the professional norm for display of museum data.

**Comment by workergnome** [comment]
Agreed.  I believe we've addressed the display aspect of this problem.  

We calculate day-specific timespans because of limitations of the data repository around sorting and calculating, but we would prefer there being a display date, and the display date should be as the museum has recorded that date.
